# Generated by Django 4.0.6 on 2022-07-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='post',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(blank='true', null='true'),
        ),
    ]
